CREATE DATABASE IF NOT EXISTS teste_dev;
USE teste_dev;

CREATE TABLE leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone TEXT NOT NULL,
  website TEXT NOT NULL,
  data_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
